const APP_DATA = [
  {
    "influencer_id": 1,
    "influencer_name": "Chelsea Gessner",
    "state": "AK",
    "region": "West",
    "blog_display": "www.chelsandco.com",
    "blog_url": "http://bit.ly/2cpMvF6",
    "statement": "Living in Juneau, I have learned to keep it casual and comfy. It rains the majority of the year so a jacket is always a must, paired with jeans and a tee. On a warmer day you can catch me wearing a dress or romper paired with a sun hat and sandals.",
    "influencer_image": "Chelsea_Gessner_AK_12.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Cocoon Dress for Women",
    "look1_mpn": 281214,
    "look2_cat_name": "Accessories",
    "look2_prod_name": "Classic Tall Tote for Women",
    "look2_mpn": 221581,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Felt Floppy Hat for Women",
    "look3_mpn": 223882,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Faux-Leather Double-Strap Sandals for Women",
    "look4_mpn": 205468
  },
  {
    "influencer_id": 2,
    "influencer_name": "Laurie Caroline Bramlett",
    "state": "AL",
    "region": "Southeast",
    "blog_display": "www.lcbstyle.com",
    "blog_url": "http://bit.ly/2bWBbT4",
    "statement": "From the city to the country to the beach to the lake, Alabama has a wide variety of beautiful landscapes that are the perfect backdrop to everyday life and style, and each of these different places has influenced my daily fashion choices.",
    "influencer_image": "caroline_bramlett_al_1.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Mid-Rise Rockstar Built-In Sculpt Jeans for Women",
    "look1_mpn": 815208,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Boyfriend Chambray Shirt for Women",
    "look2_mpn": 283572,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Felt Floppy Hat for Women",
    "look3_mpn": 223882,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 3,
    "influencer_name": "Rochelle Johnson",
    "state": "AR",
    "region": "Southeast",
    "blog_display": "www.beauticurve.com",
    "blog_url": "http://bit.ly/2bUq4ar",
    "statement": "Little Rock is small but it has a ton of personality and culture. I'm wearing a classic open-front jacket but the print just makes a stylish statement. I love that it can be worn a thousand different ways.",
    "influencer_image": "ro_johnson_ar_7.jpg",
    "look1_cat_name": "Outerwear and Sweaters",
    "look1_prod_name": "Jacquard Plus-Size Open-Front Jacket",
    "look1_mpn": 273898,
    "look2_cat_name": "Tops",
    "look2_prod_name": "V-Neck Plus-Size Shirred-Back Blouse",
    "look2_mpn": 394392,
    "look3_cat_name": "Denim",
    "look3_prod_name": "Raw-Edge Plus-Size Cropped Flare Jeans",
    "look3_mpn": 297243,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 4,
    "influencer_name": "Becki Crosby",
    "state": "AZ",
    "region": "Southwest",
    "blog_display": "www.whippycake.com",
    "blog_url": "http://bit.ly/2cktxCL",
    "statement": "I love how the Arizona heat has influenced my wardrobe and style because it has motivated me to keep my look simple and uncomplicated. I'm talking about dialing it back to effortless t-shirt and jean combos.",
    "influencer_image": "becki_crosby_az_8.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Boyfriend Mid-Rise Straight Ankle Jeans for Women",
    "look1_mpn": 286768,
    "look2_cat_name": "Tees",
    "look2_prod_name": "Relaxed Hi-Lo V-Neck Linen Tee for Women",
    "look2_mpn": 218723,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Ghillie-Tie Gladiator Sandals for Women",
    "look3_mpn": 219068,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Classic Aviator-Style Sunglasses for Women",
    "look4_mpn": 286089
  },
  {
    "influencer_id": 5,
    "influencer_name": "Tim Melideo",
    "state": "CA",
    "region": "West",
    "blog_display": "www.stayclassicblog.com",
    "blog_url": "http://bit.ly/2clGOvf",
    "statement": "San Diego weather is great all year round, with most days seeing nothing but sun. Having moved from Los Angeles, I've found my style to be even more casual, and definitely influenced by vintage surf, skate, and music culture.",
    "influencer_image": "tim_melideo_ca_1.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Built-In Flex Skinny Jeans for Men",
    "look1_mpn": 222154,
    "look2_cat_name": "Shoes",
    "look2_prod_name": "Sueded Mid-Top Sneakers for Men",
    "look2_mpn": 218674,
    "look3_cat_name": "Tees",
    "look3_prod_name": "Henley Tee for Men",
    "look3_mpn": 295017,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 6,
    "influencer_name": "Carolina Hellal",
    "state": "CO",
    "region": "West",
    "blog_display": "www.chictalkch.com",
    "blog_url": "http://bit.ly/2cksfb5",
    "statement": "Jeans have always been my go-to for casual outfits. I love pairing my jeans with versatile tops that can be easily dressed up or down. My current lifestyle is very casual, and that's why I'm always looking for those transitional day-to-night pieces.",
    "influencer_image": "Carolina_Hellal_co_5.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "High-Neck Tank for Women",
    "look1_mpn": 118761,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Jacquard Open-Front Jacket",
    "look2_mpn": "",
    "look2_url": "http://oldnavy.gap.com/browse/category.do?cid=55474&mlink=0,people_50states&tid=onsm004625",
    "look3_cat_name": "Denim",
    "look3_prod_name": "Mid-Rise Built-In-Sculpt Rockstar Jeans for Women",
    "look3_mpn": 285842,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 7,
    "influencer_name": "Christina Tarabishy",
    "state": "CT",
    "region": "Northeast",
    "blog_display": "www.ohsoglam.com",
    "blog_url": "http://bit.ly/2bXguIu",
    "statement": "It's all about the changing seasons in Connecticut. Lightweight layers go a long way, and I definitely get use out of them year-round! When the weather cools off, I love to mix rich neutrals and textures with wardrobe basics for a go-to uniform!",
    "influencer_image": "christina_tarabishy_CT_4.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Mid-Rise Cropped Flare Jeans for Women",
    "look1_mpn": 222245,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Long Open-Front Cardigan",
    "look2_mpn": 335155,
    "look3_cat_name": "Tees",
    "look3_prod_name": "Relaxed V-neck Tee for Women",
    "look3_mpn": "151621",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },  
  {
    "influencer_id": 8,
    "influencer_name": "Katherine Tabinowski",
    "state": "DE",
    "region": "Northeast",
    "blog_display": "www.styletabblog.com",
    "blog_url": "http://bit.ly/2cpMSzJ",
    "statement": "Growing up in Delaware, with its year-round unpredictable weather, I mastered the art of layering. It's my go-to styling trick for seasonal transitions. My style consists of elevated pieces that are versatile, unique, and comfortable.",
    "influencer_image": "katherine_tabinowski_de_2.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Sleeveless Swing Dress for Women",
    "look1_mpn": 281330,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Field Jacket for Women",
    "look2_mpn": 274737,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Side-Zip Boots for Women",
    "look3_mpn": 275755,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 9,
    "influencer_name": "Chante Burkett",
    "state": "FL",
    "region": "SouthEast",
    "blog_display": "www.everythingcurvyandchic.com",
    "blog_url": "http://bit.ly/2cdPHHY",
    "statement": "Florida fashion calls for breathable clothing. The Florida heat can be oppressive, and our seasons don't really change. Here in Miami, once fall hits we rock neutrals like crazy, and we always have a light jacket nearby for the chilly nights.",
    "influencer_image": "Chante_Bryant_FL_12.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Utility Romper for Women",
    "look1_mpn": 134533,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Denim Jacket for Women",
    "look2_mpn": 714108,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Pointy-Toe Lace-Up Flats for Women",
    "look3_mpn": 275668,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Classic Tall Tote for Women",
    "look4_mpn": 221581
  },
 {
    "influencer_id": 10,
    "influencer_name": "Monica Awe-Etuk",
    "state": "GA",
    "region": "Southeast",
    "blog_display": "www.awedbymonica.com",
    "blog_url": "http://bit.ly/2cktHdc",
    "statement": "If there is one thing I enjoy about living in Atlanta, it would be that you can never go wrong with a great pair of jeans. Color pops add a little Southern charm, making this outfit perfect for brunch, dinner, or hanging out with friends!",
    "influencer_image": "monica_awe.etuk_ga_3.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "White Boyfriend Shirt for Women",
    "look1_mpn": 283507,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Boyfriend Mid-Rise Straight Ankle Jeans for Women",
    "look2_mpn": 286768,
    "look3_cat_name": "Outerwear and Sweaters",
    "look3_prod_name": "Denim Jacket for Women",
    "look3_mpn": 714109,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 11,
    "influencer_name": "Emma Wo",
    "state": "HI",
    "region": "West",
    "blog_display": "www.thealohababe.com",
    "blog_url": "http://bit.ly/2cpN55K",
    "statement": "My style is inspired by my hometown of Honolulu, Hawaii. Old Navy has tons of different styles and pieces to fit every look. I knew I wanted to incorporate something floral, and as a plus, this top helped me beat the Hawaiian heat!",
    "influencer_image": "emma_wo_hi_2.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Printed Swing Smock Tank for Women",
    "look1_mpn": 285098,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Built-In Sculpt Jeans for Women",
    "look2_mpn": 815208,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Reversible Faux-Leather Tote",
    "look3_mpn": 173181,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Felt Floppy Hat for Women",
    "look4_mpn": 223882
  },
  {
    "influencer_id": 12,
    "influencer_name": "Samantha McClelland",
    "state": "IA",
    "region": "Midwest",
    "blog_display": "www.thebrunetteone.com",
    "blog_url": "http://bit.ly/2bIUKkb",
    "statement": "We look for versatility in our wardrobe that can easily transition between days spent in the office, wandering around the Farmer's Market, catching the latest restaurant opening in Western Gateway Park, or going to a concert in the East Village.",
    "influencer_image": "samantha_mcclelland_ia_5.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "High-Neck Trapeze Tank for Women",
    "look1_mpn": 285611,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Super Skinny Ankle Jeans",
    "look2_mpn": 209110,
    "look3_cat_name": "Tops",
    "look3_prod_name": "Long Open-Front Cardigan",
    "look3_mpn": 335155,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Classic Faux-Leather Tote for Women",
    "look4_mpn": 221583
  },
  {
    "influencer_id": 13,
    "influencer_name": "Kirsten Grove",
    "state": "ID",
    "region": "West",
    "blog_display": "www.simplygrove.com",
    "blog_url": "http://bit.ly/2c51yqy",
    "statement": "When you're surrounded by rolling hills, mountains and beautiful trees, you can be a little less serious and a little more bohemian. Throwing denim jackets over little black dresses is our jam.",
    "influencer_image": "kirsten_grove_id_2.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Swing Tee for Women (similar)",
    "look1_mpn": 221040,
    "look2_cat_name": "Skirts",
    "look2_prod_name": "Jersey Pencil Midi Skirt for Women",
    "look2_mpn": 477749,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Oversized Leopard-Print Sunglasses for Women",
    "look3_mpn": 286094,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 14,
    "influencer_name": "Jennifer Lake",
    "state": "IL",
    "region": "Midwest",
    "blog_display": "www.stylecharade.com",
    "blog_url": "http://bit.ly/2c52lYv",
    "statement": "Living somewhere with all four seasons requires clothing and accessory options galore. I love this classic Old Navy denim jacket, and I paired it with an Old Navy pink floral dress, blue clutch and booties.",
    "influencer_image": "jennifer_lake_il_3.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Cami Dress for Women ",
    "look1_mpn": 281354,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Cropped Denim Jacket",
    "look2_mpn": 151708,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Ankle Boot",
    "look3_mpn": 225507,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Faux-Suede Cosmetic Case",
    "look4_mpn": 338034
  },
  {
    "influencer_id": 15,
    "influencer_name": "Erin Loechner",
    "state": "IN",
    "region": "Midwest",
    "blog_display": "www.DesignforMankind.com",
    "blog_url": "http://bit.ly/2bXgkkp",
    "statement": "We've got laidback weekends, sprawling cornfields, good manners and a healthy stash of peanut butter pie recipes in nearly every cupboard. When it comes to personal style, I choose my outfits like I choose my hometown: thoughtful and simple.",
    "influencer_image": "erin_loechner_in_6.png",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Sleeveless Pintuck Swing Dress for Women",
    "look1_mpn": 281282,
    "look2_cat_name": "Shoes",
    "look2_prod_name": "T-Strap Clogs for Women",
    "look2_mpn": 275695,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Textured Stitch Linear Scarf for Women",
    "look3_mpn": 219187,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Mini-Saddle Bag for Women",
    "look4_mpn": 294041
  },
  {
    "influencer_id": 16,
    "influencer_name": "Alissa Futhey",
    "state": "KS",
    "region": "Midwest",
    "blog_display": "www.theadoredlife.com",
    "blog_url": "http://bit.ly/2cpMW2i",
    "statement": "Growing up, I never appreciated the simple beauty of the spacious, open fields. Now, as an adult, I find myself gravitating towards easy, breezy, floral dresses that remind me of the gorgeous landscapes across Kansas.",
    "influencer_image": "alissa_futhey_KS_12.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "V-Neck Shift Dress for Women",
    "look1_mpn": 132890,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Cropped Denim Jacket",
    "look2_mpn": 151708,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Pointy-Toe Lace-Up Flats for Women",
    "look3_mpn": 434365,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 17,
    "influencer_name": "Josh Johnson",
    "state": "KY",
    "region": "Southeast",
    "blog_display": "www.thekentuckygent.com",
    "blog_url": "http://bit.ly/2bQJ2A6",
    "statement": "Kentucky is a great place to call home, but our weather has been known to be a fickle beast on occasion. I've learned to be prepared by never leaving the house without a light jacket or something to layer over a tee!",
    "influencer_image": "josh_johnson_ky_9.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Built-In Flex Skinny Jeans for Men",
    "look1_mpn": 338206,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Bomber Jacket for Men",
    "look2_mpn": 332700,
    "look3_cat_name": "Tees",
    "look3_prod_name": "Pocket Crew-Neck Tee for Men",
    "look3_mpn": 478461,
    "look4_cat_name": "Tops",
    "look4_prod_name": "Chambray Slim-Fit Shirt",
    "look4_mpn": 118566
  },  
  {
    "influencer_id": 18,
    "influencer_name": "Dabito Luong",
    "state": "LA",
    "region": "Southeast",
    "blog_display": "www.oldbrandnew.com",
    "blog_url": "http://bit.ly/2bNNEa7",
    "statement": "I like to pair a linen shirt (loosely rolled up) with dark denim for a laid-back look, then dress it up with oxfords for an effortless style. Also, weather can be unpredictable in New Orleans, so my style involves a must-have yellow rain jacket!",
    "influencer_image": "dabito_luong_la_4.jpg",
    "look1_cat_name": "Tees",
    "look1_prod_name": "Garment-Dyed Crew-Neck Pocket Tee for Men",
    "look1_mpn": 219597,
    "look2_cat_name": "Shoes",
    "look2_prod_name": "Sueded Oxfords for Men",
    "look2_mpn": 332728,
    "look3_cat_name": "Outerwear and Sweaters",
    "look3_prod_name": "Lightweight Dobby Anorak for Men",
    "look3_mpn": 333019,
    "look4_cat_name": "Denim",
    "look4_prod_name": "Built-In-Flex Slim Jeans for Men",
    "look4_mpn": 220063
  },
  {
    "influencer_id": 19,
    "influencer_name": "Kerrie Burke",
    "state": "MA",
    "region": "Northeast",
    "blog_display": "www.kerriemburke.com",
    "blog_url": "http://bit.ly/2cqvDhw",
    "statement": "The summer-fall transition can be a tricky one and it's no different here in Boston. One day you're feeling that chill and the next those temps are creeping into the high nineties\u2014eek! My trick for staying cool (or cozy) in style? Layers!",
    "influencer_image": "Kerrie_Burke_ma-1.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Cami Dress for Women",
    "look1_mpn": 281354,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Field Jacket for Women",
    "look2_mpn": 274737,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Ankle Boot for Women",
    "look3_mpn": 225507,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 20,
    "influencer_name": "Caitlin Kruse",
    "state": "MD",
    "region": "Northeast",
    "blog_display": "www.stylewithinreach.net",
    "blog_url": "http://bit.ly/2cpQbqB",
    "statement": "Living in my hometown of Annapolis has certainly influenced my style and fashion choices over the years. We are known more for our nautical feel and preppy look. Old Navy is one of my go-to sources to find these pieces that fit with my style.",
    "influencer_image": "Caitlin_Kruse_MD_3.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Relaxed Heavy-Knit Boat-Neck Tee for Women",
    "look1_mpn": 335298,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Cropped Flare Jeans for Women",
    "look2_mpn": 222245,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Sueded Double-Zip Crossbody Bag for Women",
    "look3_mpn": 145688,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 21,
    "influencer_name": "Elana Loo",
    "state": "ME",
    "region": "Northeast",
    "blog_display": "www.elanaLoo.com",
    "blog_url": "http://bit.ly/2cktWF8",
    "statement": "Living in Maine, the more classic, timeless side of my style has surfaced. I have learned that you can put your own twist on the classics to make them approachable, modern, and true to your style!",
    "influencer_image": "Elana_Jadallah_ME_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Printed Swing Smock Tank for Women",
    "look1_mpn": 285098,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Distressed Jeans",
    "look2_mpn": 815202,
    "look3_cat_name": "Tops",
    "look3_prod_name": "Slit-Back Gauzy Boyfriend Shirt for Women",
    "look3_mpn": 209252,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 22,
    "influencer_name": "Lisa Marie Prang",
    "state": "MI",
    "region": "Midwest",
    "blog_display": "www.lmpcollections.com",
    "blog_url": "http://bit.ly/2bIlQlw",
    "statement": "My Old Navy style has been influenced greatly due to my hometown of Williamston. Open fields and grassy parks surround us, and those elements have greatly influenced this look! Floral is my go-to print and layering is a must!",
    "influencer_image": "lisa_prang_mi_2.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "V-Neck Shift Dress for Women",
    "look1_mpn": 132890,
    "look2_cat_name": "Shoes",
    "look2_prod_name": "Sueded Ankle Boot for Women",
    "look2_mpn": 225507,
    "look3_cat_name": "Tops",
    "look3_prod_name": "Long Open-Front Cardigan",
    "look3_mpn": 335155,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Glossy Sunglasses for Women",
    "look4_mpn": 286584
  },
  {
    "influencer_id": 23,
    "influencer_name": "Maria Vizuete",
    "state": "MN",
    "region": "Midwest",
    "blog_display": "www.miamiamine.com",
    "blog_url": "http://bit.ly/2cdhqEO",
    "statement": "It's true that Minnesotans are nice and it's reflected in our style which is approachable, casual and classic. I start with a great pair of jeans. I like to mix in an edgier piece like this moto jacket and balance it with a classic like this striped top.",
    "influencer_image": "maria_vizuete_mn_1.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "High-Rise Rockstar Distressed Skinny Jeans for Women",
    "look1_mpn": 208345,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Relaxed Boat-Neck Tee for Women",
    "look2_mpn": 335302,
    "look3_cat_name": "Outerwear and Sweaters",
    "look3_prod_name": "Moto Jacket for Women",
    "look3_mpn": 274773,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Sueded Side-Zip Boots for Women",
    "look4_mpn": 275755
  },
  {
    "influencer_id": 24,
    "influencer_name": "Sarah Ruhlman",
    "state": "MO",
    "region": "Midwest",
    "blog_display": "www.sarahscoop.com",
    "blog_url": "http://bit.ly/2bYQl9C",
    "statement": "Whether I'm creating a bold look or a more basic transitional outfit like this one, in Missouri we always keep it stylish. For this specific look I was all about embracing the basics, keeping me comfortable, chic and verstaile.",
    "influencer_image": "sarah_ruhlman_MO_7.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Textured Pullover for Women",
    "look1_mpn": 274807,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Low-Rise Rockstar Jeggings for Women",
    "look2_mpn": 730770,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Side-Zip Boots for Women",
    "look3_mpn": 275755,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Felt Floppy Hat for Women",
    "look4_mpn": 223882
  },
  {
    "influencer_id": 25,
    "influencer_name": "Taran Kaur",
    "state": "MS",
    "region": "Southeast",
    "blog_display": "www.thatssotaran.com",
    "blog_url": "http://bit.ly/2ck9AcU",
    "statement": "Comfort doesn't come easier than a basic white tee and some cut-offs. I paired my outfit with a pair of black heeled sandals and a field jacket to fight the unpredictable Mississippi weather.",
    "influencer_image": "taran_kaur_ms_2.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Oversized Tee for Women",
    "look1_mpn": 119858,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Field Jacket for Women",
    "look2_mpn": 274737,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Double-Strap Clogs for Women",
    "look3_mpn": 218292,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Large Double-Zip Crossbody Bag for Women",
    "look4_mpn": 596256
  },
  {
    "influencer_id": 26,
    "influencer_name": "McKenna Munden",
    "state": "MT",
    "region": "West",
    "blog_display": "www.mckennamunden.com",
    "blog_url": "http://bit.ly/2cktuXO",
    "statement": "Missoula feels very much like a hometown but with a trendy flair. There is always something new to experience. With the comfort of the grey-wash jeans and the classic lines of the v-neck tank, I am able to explore the city in style and comfort.",
    "influencer_image": "mckenna_munden_mt_15.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Shirred-Back Blouse for Women",
    "look1_mpn": 285799,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Grey-Wash Rockstar Jeans for Women",
    "look2_mpn": 334306,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Plaid Fringe Blanket Scarf",
    "look3_mpn": 334444,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Faux-Leather Foldover Crossbody Bag",
    "look4_mpn": 136952
  },
  {
    "influencer_id": 27,
    "influencer_name": "Emily Helm",
    "state": "NC",
    "region": "Southeast",
    "blog_display": "www.lifewithemilyblog.com",
    "blog_url": "http://bit.ly/2cpMiSo",
    "statement": "The best part of being from North Carolina is that you can travel a short distance and be at either the beach or the mountains. My city is pretty relaxed so I like to mix classic pieces with more on-trend pieces, like flares and chunky heels.",
    "influencer_image": "Emily_Helm_NC_4.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Boyfriend Plaid Shirt for Women",
    "look1_mpn": 284379,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Skinny Jeans for Women",
    "look2_mpn": 288661,
    "look3_cat_name": "",
    "look3_prod_name": "",
    "look3_mpn": "",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 28,
    "influencer_name": "Molly Yeh",
    "state": "ND",
    "region": "Midwest",
    "blog_display": "www.mynameisyeh.com",
    "blog_url": "http://bit.ly/2bYR22R",
    "statement": "The flat golden wheat fields of this region, our massive open skies, and small quaint towns where everyone knows each other keep us humble and not too flashy with our style. Chunky knitted sweaters in neutrals and earth tones are my go-to staples.",
    "influencer_image": "molly_yeh_nd_2.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Hi-Lo Open-Knit Pointelle Sweater for Women",
    "look1_mpn": 227551,
    "look2_cat_name": "Tops",
    "look2_prod_name": "White Boyfriend Shirt for Women",
    "look2_mpn": 283507,
    "look3_cat_name": "Denim",
    "look3_prod_name": "Mid-Rise Rockstar Built-In Sculpt Jeggings for Women",
    "look3_mpn": 335271,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Sueded Ankle Boot for Women",
    "look4_mpn": 225507
  },
  {
    "influencer_id": 29,
    "influencer_name": "Sara Sabaliauskas",
    "state": "NE",
    "region": "Midwest",
    "blog_display": "www.sabbystyle.com",
    "blog_url": "http://bit.ly/2bGbEid",
    "statement": "Born and raised in Omaha, my style is a direct reflection of my Midwestern roots. Mixing classic prints such as stripes, with quintessential Midwestern plaid, is how I combine my love for home and fashion.",
    "influencer_image": "sara_sabaliauskas_NE_4.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Mid-Rise Destructed Rockstar Jeans for Women",
    "look1_mpn": 336524,
    "look2_cat_name": "Accessories",
    "look2_prod_name": "Felt Floppy Hat for Women",
    "look2_mpn": 223882,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Ankle Boot for Women",
    "look3_mpn": 225507,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Classic Tall Tote for Women",
    "look4_mpn": 221581
  },
  {
    "influencer_id": 30,
    "influencer_name": "Jennifer Miller",
    "state": "NH",
    "region": "Northeast",
    "blog_display": "www.jennifer-blake.com",
    "blog_url": "http://bit.ly/2cpOrNZ",
    "statement": "New Hampshire is the granite state, known for its beautiful scenery and ever-changing temperatures. It can be 50 degrees in the morning and 90 degrees by the afternoon. Old Navy makes layering easy with its versatile pieces, from scarves to lightweight sweaters.",
    "influencer_image": "jennifer_miller_nh_1.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Mid-Rise Rockstar Destructed Skinny Jeans for Women",
    "look1_mpn": 141904,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Hi-Lo Open-Knit Pointelle Sweater for Women",
    "look2_mpn": 227551,
    "look3_cat_name": "",
    "look3_prod_name": "",
    "look3_mpn": "",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 31,
    "influencer_name": "Naty Michele",
    "state": "NJ",
    "region": "Northeast",
    "blog_display": "natymichele.com",
    "blog_url": "http://bit.ly/2ckv8IC",
    "statement": "I think that the simplicity in my style as well as my love for color and prints come from Jersey. We are known to be bold and loud at times! Old Navy's great selection of basics and trendier items helped me to achieve the look I was going for.",
    "influencer_image": "naty_michele_nj_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Open-Knit Cocoon Cardi For Women",
    "look1_mpn": 225962,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Distressed Jeans",
    "look2_mpn": 815202,
    "look3_cat_name": "Tops",
    "look3_prod_name": "Printed Vneck Cut-Out Tank for Women",
    "look3_mpn": 285723,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Sueded Double-Zip Crossbody Bag for Women",
    "look4_mpn": 145688
  },
  {
    "influencer_id": 32,
    "influencer_name": "Ciera Hudson",
    "state": "NM",
    "region": "Southwest",
    "blog_display": "www.yourstrulyciera.com",
    "blog_url": "http://bit.ly/2cqwAGJ",
    "statement": "Albuquerque is a vibrant city, with rich history, unique architecture and green chile on every menu! So that's why I love pairing basics with bright colors, and choosing fun accessories that match the city walls around me. My one-stop shop? Old Navy, of course!",
    "influencer_image": "ciera_hudson_nm_40.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Boyfriend Scoop Tee for Women",
    "look1_mpn": 335290,
    "look2_cat_name": "Denim",
    "look2_prod_name": "High-Rise Rockstar Distressed Skinny Jeans for Women",
    "look2_mpn": "",
    "look2_url": "http://oldnavy.gap.com/browse/product.do?cid=85732&vid=1&pid=208345022&mlink=0,people_50states&tid=onsm004625",
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Block Heel Sandals for Women",
    "look3_mpn": 218274,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 33,
    "influencer_name": "Jamie Hatcher",
    "state": "NV",
    "region": "West",
    "blog_display": "www.treatsandtrendsblog.com",
    "blog_url": "http://bit.ly/2bN2Se2",
    "statement": "My sense of style is influenced by the cool, urban vibes of downtown Las Vegas. The creative, playful atmosphere inspires me to have fun with fashion. These light layers are also perfect for fall, since it never gets too cold here in the desert.",
    "influencer_image": "jamie_hatcher_nv_3.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Lace-Sleeve Gauze Boho Blouse for Women",
    "look1_mpn": 218407,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Built-In Sculpt Jeans for Women",
    "look2_mpn": 815208,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Pointy Ballet Flats for Women",
    "look3_mpn": 146204,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Classic Tall Tote for Women",
    "look4_mpn": 221581
  },
  {
    "influencer_id": 34,
    "influencer_name": "Christine Petric",
    "state": "NY",
    "region": "Northeast",
    "blog_display": "www.viewfrom5ft2.com",
    "blog_url": "http://bit.ly/2bYRMoM",
    "statement": "New York City is one of the greatest places in the entire world for fashion inspiration. I think it's the hustle and bustle of the city that lends to an ease and effortlessness that has started to rub off on me and my style!",
    "influencer_image": "christine_petric_NY_04.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Utility Romper for Women",
    "look1_mpn": 134533,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Denim Jacket for Women",
    "look2_mpn": 714109,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Classic Faux-Leather Tote for Women",
    "look3_mpn": 221583,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 35,
    "influencer_name": "Candace Read",
    "state": "OH",
    "region": "Midwest",
    "blog_display": "www.liveloveandread.com",
    "blog_url": "http://bit.ly/2bWceEz",
    "statement": "As the country's third fashion capital, Columbus' fashion is classic, yet trendy, just like the nature of the city. Embracing the effortless vibe that Ohioans are known for, it's the attention to detail that makes our culture and fashion notable.",
    "influencer_image": "candace_read_OH_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Long Open-Front Cardigan",
    "look1_mpn": 335155,
    "look2_cat_name": "Tops",
    "look2_prod_name": "High-Neck Trapeze Tank for Women",
    "look2_mpn": 285611,
    "look3_cat_name": "Denim",
    "look3_prod_name": "Pixie Mid-Rise Ankle Pants for Women",
    "look3_mpn": 120007,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Large Double-Zip Crossbody Bag for Women",
    "look4_mpn": 596256
  },
  {
    "influencer_id": 36,
    "influencer_name": "Allyson Noriega",
    "state": "OK",
    "region": "Southwest",
    "blog_display": "www.allysoninwonderland.com",
    "blog_url": "http://bit.ly/2cktGWF",
    "statement": "Most of the country has to deal with days of extreme heat or cold, but few of us have to plan for both of them... on the same day. Most days I love the ease of a dress, like this one from Old Navy, because it's easy to layer upon.",
    "influencer_image": "Ally_Noriega_OK_2.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "V-Neck Shift Dress for Women",
    "look1_mpn": 132890,
    "look2_cat_name": "Shoes",
    "look2_prod_name": "Sueded Side-Zip Boots for Women",
    "look2_mpn": 275755,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Classic Tall Tote for Women",
    "look3_mpn": 221581,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 37,
    "influencer_name": "Crystalin Marie Da Silva",
    "state": "OR",
    "region": "West",
    "blog_display": "www.crystalinmarie.com",
    "blog_url": "http://bit.ly/2ckt6IJ",
    "statement": "Boyfriend jeans are a must for me and I love pairing them with stripe tees for a classic look with a modern twist. Flats are also essential in a city that involves a ton of walking. These lace-ups are a great way to add some flair to a casual look.",
    "influencer_image": "Crystalin_An_OR_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Relaxed Boat-Neck Tee for Women",
    "look1_mpn": 335302,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Boyfriend Shirt-Jacket for Women",
    "look2_mpn": 283548,
    "look3_cat_name": "Denim",
    "look3_prod_name": "Boyfriend Mid-Rise Straight Ankle Jeans for Women",
    "look3_mpn": 286768,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Pointy-Toe Lace-Up Flats for Women",
    "look4_mpn": 434365
  },
  {
    "influencer_id": 38,
    "influencer_name": "Sydney Carver",
    "state": "PA",
    "region": "Northeast",
    "blog_display": "www.summerwind.com",
    "blog_url": "http://bit.ly/2cpOBVJ",
    "statement": "Pittsburgh has the most bridges of not only any city in Pennsylvania, but in the entire world! Throughout day-to-day life, crossing a bridge is the norm, so being comfortable is a must, and these Rockstar Skinny Jeans are always my go-to denim.",
    "influencer_image": "Sydney_Carver_PA_2.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Relaxed Boat-Neck Tee for Women",
    "look1_mpn": 335302,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Chambray Button-Down Shirt",
    "look2_mpn": 120262,
    "look3_cat_name": "Denim",
    "look3_prod_name": "Mid-Rise Rockstar Skinny Jeans for Women",
    "look3_mpn": 288661,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Sueded Side-Zip Boots for Women",
    "look4_mpn": 275755
  },
  {
    "influencer_id": 39,
    "influencer_name": "Alana Rodriguez",
    "state": "RI",
    "region": "Northeast",
    "blog_display": "www.thestylebrunch.com",
    "blog_url": "http://bit.ly/2cpRHJ4",
    "statement": "I feel that the beautiful landscaping and the architecture in Rhode Island reflects in the people's sense of artistic style. To transition into fall fashion, Old Navy provides great statement pieces that are whimsical and perfect for layering.",
    "influencer_image": "alana_rodriguez_ri_14.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Classic Shirt for Women",
    "look1_mpn": 119384,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Sateen Skinny Jeans for Women",
    "look2_mpn": 334455,
    "look3_cat_name": "",
    "look3_prod_name": "",
    "look3_mpn": "",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 40,
    "influencer_name": "Chassity Evans",
    "state": "SC",
    "region": "Southeast",
    "blog_display": "www.looklingerlove.com",
    "blog_url": "http://bit.ly/2chdanZ",
    "statement": "I find that flats are the most convenient for navigating the cobblestone streets of Charleston. Strappy sandals in the summer and ballet flats in the fall are favorites of mine!",
    "influencer_image": "chassity_evans_sc_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Classic Plaid Shirt for Women",
    "look1_mpn": 283422,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Mid-Rise Rockstar Built-In Sculpt Jeans for Women",
    "look2_mpn": 815208,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Sueded Pointy Ballet Flats for Women",
    "look3_mpn": 146204,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Mini-Saddle Bag for Women",
    "look4_mpn": 294041
  },
  {
    "influencer_id": 41,
    "influencer_name": "Maren Jensen",
    "state": "SD",
    "region": "Midwest",
    "blog_display": "www.midwestinstyle.com",
    "blog_url": "http://bit.ly/2cpOY2m",
    "statement": "I was drawn to these adorable Old Navy jeans because of the patch detail. I am able to easily take them from a laid-back afternoon at Falls Park in downtown Sioux Falls to an evening wandering the plains.",
    "influencer_image": "maren_jensen_sd_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Relaxed Long and Lean Tunic Tee for Women",
    "look1_mpn": 283204,
    "look2_cat_name": "Denim",
    "look2_prod_name": "Boyfriend Mid-Rise Straight Jeans for Women",
    "look2_mpn": 131542,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Felt Floppy Hat for Women",
    "look3_mpn": 223882,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 42,
    "influencer_name": "Laura Boswell",
    "state": "TN",
    "region": "Southeast",
    "blog_display": "www.walkinginmemphisinhighheels.com",
    "blog_url": "http://bit.ly/2bHQuPn",
    "statement": "Memphis has definitely shaped my style over the years.  With the humidity this time of year, I love to wear lightweight, flowy and casual dresses, pack a hat to cover up my frizz, and rock a great pair of heels.",
    "influencer_image": "Laura_Boswell_TN_1.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Knit Swing Dress for Women (Similar)",
    "look1_mpn": 281334,
    "look2_cat_name": "Accessories",
    "look2_prod_name": "Felt Floppy Hat for Women",
    "look2_mpn": 223882,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Mini-Saddle Bag for Women",
    "look3_mpn": 294041,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 43,
    "influencer_name": "Amy Havins",
    "state": "TX",
    "region": "Southwest",
    "blog_display": "www.dallaswardrobe.com",
    "blog_url": "http://bit.ly/2bUqrSr",
    "statement": "I learned at an early age that when it comes to Dallas fashion, you should always plan for the weather (Texas is HOT or COLD). Climate control indoors does not exist and denim is the perfect wardrobe staple to take from day to night.",
    "influencer_image": "amy_havins_tx_1.jpg",
    "look1_cat_name": "Denim",
    "look1_prod_name": "Mid-Rise Rockstar Built-In Sculpt Jeans for Women",
    "look1_mpn": 815208,
    "look2_cat_name": "Tops",
    "look2_prod_name": "High Neck Trapeze Tank for Women",
    "look2_mpn": 285611,
    "look3_cat_name": "Outerwear and Sweaters",
    "look3_prod_name": "Sweater Fleece Moto Jacket for Women",
    "look3_mpn": 340623,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Ankle-Strap D'Orsay Flats for Women",
    "look4_mpn": 140436
  },
  {
    "influencer_id": 44,
    "influencer_name": "Sandy Chang",
    "state": "UT",
    "region": "West",
    "blog_display": "www.sandyalamode.com",
    "blog_url": "http://bit.ly/2cpMBg8",
    "statement": "I think people in Utah tend to gravitate towards wearing neutral colors that mimic the colors of the gorgeous mountains that surround our every day life. I love to add either a subtle or bold pop of color to my outfit to personalize my style.",
    "influencer_image": "sandy_chang_ut_1.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Cami Dress for Women",
    "look1_mpn": 281354,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Long Open-Front Cardigan",
    "look2_mpn": 335155,
    "look3_cat_name": "Accessories",
    "look3_prod_name": "Felt Floppy Hat for Women",
    "look3_mpn": 223882,
    "look4_cat_name": "Shoes",
    "look4_prod_name": "Sueded Side-Zip Boots for Women",
    "look4_mpn": 275755
  },
  {
    "influencer_id": 45,
    "influencer_name": "Natalie Pinto",
    "state": "VA",
    "region": "Southeast",
    "blog_display": "www.thefashionablybroke.com",
    "blog_url": "http://bit.ly/2cpQm57",
    "statement": "Living in Virginia means having access to the \"big city,\" as well as the great outdoors. During the week I rely heavily on closet staples, like a military jacket that can be mixed and matched with several outfits, and transitioned from day to night.",
    "influencer_image": "Natalie_Pinto_VA_3.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Cami Dress for Women",
    "look1_mpn": 281354,
    "look2_cat_name": "Outerwear and Sweaters",
    "look2_prod_name": "Field Jacket for Women",
    "look2_mpn": 274737,
    "look3_cat_name": "Shoes",
    "look3_prod_name": "Peep Toe Flats for Women",
    "look3_mpn": "",
    "look3_url": "http://oldnavy.gap.com/browse/product.do?cid=55148&vid=1&pid=140587032&mlink=0,people_50states&tid=onsm004625",
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Double-Zip Crossbody Bag for Women",
    "look4_mpn": 977375
  },
  {
    "influencer_id": 46,
    "influencer_name": "Juliana Summers",
    "state": "VT",
    "region": "Northeast",
    "blog_display": "www.littlecupofj.com",
    "blog_url": "http://bit.ly/2clIAMP",
    "statement": "I aim to keep on-trend by staying true to my easy-going roots. Typically, my everyday style in Burlington is just that\u2014everyday style. Comfy swing dresses (loving the subtle print on this one) and light outer layers make a perfect pairing.",
    "influencer_image": "juliana_summers_vt_3.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Sleeveless Swing Dress for Women",
    "look1_mpn": 281330,
    "look2_cat_name": "Accessories",
    "look2_prod_name": "Felt Floppy Hat for Women",
    "look2_mpn": "223882",
    "look3_cat_name": "Tops",
    "look3_prod_name": "Boyfriend Chambray Shirt for Women",
    "look3_mpn": "283572",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 47,
    "influencer_name": "Amanda Carter Gomes",
    "state": "WA",
    "region": "West",
    "blog_display": "www.clementinedaily.com",
    "blog_url": "http://bit.ly/2cpOuJw",
    "statement": "Seattle has a modern, minimal and laid back West Coast vibe. My wardrobe is built around key items that embrace that aesthetic while being versatile enough to go with most anything I own. I'll be rotating this denim jumpsuit for seasons to come!",
    "influencer_image": "amanda_carter_gomes_wa_5.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Denim Cami Jumpsuit for Women",
    "look1_mpn": 134620,
    "look2_cat_name": "Shoes",
    "look2_prod_name": "Sueded Double-Strap Clogs for Women",
    "look2_mpn": 218292,
    "look3_cat_name": "",
    "look3_prod_name": "",
    "look3_mpn": "",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 48,
    "influencer_name": "Lauren Felix",
    "state": "WI",
    "region": "Midwest",
    "blog_display": "www.lapetitefashionista.com",
    "blog_url": "http://bit.ly/2cpQsd1",
    "statement": "As a Florida turned Wisconsin girl, one of the things I've grown to love most is the change of seasons. I look forward to layering on the sweaters and ankle boots in fall and switching out to sundresses in the summertime!",
    "influencer_image": "lauren_felix_wi_1.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Relaxed Curve Hem Linen Tank for Women",
    "look1_mpn": 118008,
    "look2_cat_name": "Tops",
    "look2_prod_name": "Marled Cocoon Open Front For Women",
    "look2_mpn": 225972,
    "look3_cat_name": "Denim",
    "look3_prod_name": "Mid-Rise Rockstar Sateen Skinny Jeans for Women",
    "look3_mpn": 334455,
    "look4_cat_name": "Accessories",
    "look4_prod_name": "Glossy Sunglasses for Women",
    "look4_mpn": 286584
  },
  {
    "influencer_id": 49,
    "influencer_name": "Jacinda Bruno",
    "state": "WV",
    "region": "Southeast",
    "blog_display": "brunchbrainbaubles.com",
    "blog_url": "http://bit.ly/2ckuzP9",
    "statement": "My West Virginia tee shows my team spirit and my tan field jacket is an extra layer to keep me cozy during tailgates. My flares and tan booties help add to my personal girly style, yet are still comfortable to cheer on the football team all day long.",
    "influencer_image": "jacinda_bruno_wv_4.jpg",
    "look1_cat_name": "Tops",
    "look1_prod_name": "Field Jacket for Women",
    "look1_mpn": 274737,
    "look2_cat_name": "Tees",
    "look2_prod_name": "College-Team Graphic V-Neck Tee for Women",
    "look2_mpn": "",
    "look2_url": "http://oldnavy.gap.com/browse/product.do?cid=1038667&vid=1&pid=225821402&mlink=0,people_50states&tid=onsm004625",
    "look3_cat_name": "Denim",
    "look3_prod_name": "Mid-Rise Micro Flare Jeans for Women",
    "look3_mpn": 335289,
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  },
  {
    "influencer_id": 50,
    "influencer_name": "Meagan Murtagh",
    "state": "WY",
    "region": "West",
    "blog_display": "www.theeggoutwest.com",
    "blog_url": "http://bit.ly/2cttOR1",
    "statement": "My Wyoming style is all about working with the elements. Jackson Hole is a gorgeous mountain town where I spend most of my time outdoors. With hot, dry summers and cold, harsh winters, my wardrobe very much revolves around whatever season it may be.",
    "influencer_image": "meagan_murtagh_wy_211.jpg",
    "look1_cat_name": "Dresses",
    "look1_prod_name": "Embroidered Swing Dress for Women",
    "look1_mpn": 281287,
    "look2_cat_name": "",
    "look2_prod_name": "",
    "look2_mpn": "",
    "look3_cat_name": "",
    "look3_prod_name": "",
    "look3_mpn": "",
    "look4_cat_name": "",
    "look4_prod_name": "",
    "look4_mpn": ""
  }
];


export default APP_DATA;